### ISSUE TITLE
Timeout isn't working as expected

### ISSUE THREAD

**Issue by Beraliv** [sinonjs/nise#160]
**Expected behaviour**:

1. `xhr.ontimeout` is called after `xhr.timeout`
2. `xhr.triggerTimeout` is called after `xhr.timeout`

**Actual behaviour**:

1. `xhr.ontimeout` is NOT called after `xhr.timeout`
2. `xhr.triggerTimeout` is NOT called after `xhr.timeout`

**Code**:

```ts
import { expect } from 'chai';
import { createSandbox, fakeServer, FakeXMLHttpRequest } from 'sinon';

const sleep = (duration: number): Promise<void> =>
    new Promise((resolve) => {
        setTimeout(resolve, duration);
    });

describe('send', () => {
    it('should be timeout', async () => {
        const sandboxInstance = createSandbox();

        const xhr = new FakeXMLHttpRequest();
        (xhr as any).open('GET', '/');
        (xhr as any).timeout = 1_000;
        (xhr as any).triggerTimeout = sandboxInstance.spy();
        (xhr as any).send();

        let isTimeout = false;
        (xhr as any).ontimeout = () => {
            isTimeout = true;
        };

        await sleep(2_000);

        (fakeServer as any).respond();

        expect((xhr as any).triggerTimeout.getCalls().length).to.eq(1);
        expect(isTimeout).to.eq(true);
    });
});
```

**Additional data**

1. Versions:
  * `"nise": "1.4.3",`
  * `"chai": "4.2.0",`
  * `"@types/chai": "4.1.7",`
2. Might be connected to [issue](https://github.com/sinonjs/nise/issues/3) and [PR](https://github.com/sinonjs/nise/pull/4)
3. If I replace it with `XMLHttpRequest` and use latency=5s in Chrome, the test will pass
4. If I update `nise` to version `4.0.3`, it doesn't change anything

**Comment by Beraliv** [comment]
@mroderick can you please have a look at it? Is it expected?

**Comment by fatso83** [comment]
@Beraliv Could you do a quick inquiry into the test suite by grepping after "timeout" and see if there is test code that tries to document how this is supposed to work?

**Comment by Beraliv** [comment]
> @Beraliv Could you do a quick inquiry into the test suite by grepping after "timeout" and see if there is test code that tries to document how this is supposed to work?

I will check this week, sorry for the delay

**Comment by Beraliv** [comment]
Still there was no time for that
Hope I will get to that next week

**Comment by mroderick** [comment]
I've pinned this, hoping there will be updates to clarify this one way or the other.

**Comment by Beraliv** [comment]
> @Beraliv Could you do a quick inquiry into the test suite by grepping after "timeout" and see if there is test code that tries to document how this is supposed to work?

@fatso83 sorry for the late response

Let me explain what I meant.

1. I expected that timeout is supported https://github.com/sinonjs/nise/blob/fd08db8fcc59900c531d317bed92ae99be1bacc6/lib/fake-xhr/index.test.js#L343
2. After setting the timeout, I would like to hold the response longer to trigger the timeout callback - https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout#Example
3. Then I check that the callback is working as expected

So probably I shouldn't use `spy` for `triggerTimeout`, or what am I doing wrong?

**Comment by Beraliv** [comment]
@mroderick should I specify anything that can help?

**Comment by mroderick** [comment]
I'll leave it to @fatso83 to figure out :)

**Comment by fatso83** [comment]
@Beraliv I don't really have much time for open source work these days, so I would not be expecting much from me. In any case, the `nise` source code is just a few hundred lines, so it's faster to scroll through it yourself, than waiting for us to re-read it :smile_cat: I used 20 minutes or so anyway tonight to look at this and had a look at the PR you linked to, which I seemed to have merged three years ago. It seems that it is supposed to be used somewhat differently:

These two lines are important:
- https://github.com/sinonjs/nise/pull/4/files#diff-70757de66c99d2ded5472059b68b66f1R1447
- https://github.com/sinonjs/nise/pull/4/files#diff-03bee40ee9cedcff60e39b08d9f066b3R495

That means the timeout will only timeout if you run this using fake timers. Meaning stubbing out time using Sinon's fake timers. In that PR I objected to this, since I thought it was a decision that should be up to the user, not the author of the PR, but there seems to have been some kind of misunderstanding, as that restriction was actually never removed before I merged it.

In any case, it's no wonder that this does not work when you just `await` the code, as it will never run if `Date` is not stubbed. Here is an example of how to do that from the associated tests: https://github.com/sinonjs/nise/pull/4/files#diff-70757de66c99d2ded5472059b68b66f1R1505

---

A totally different story is whether this restriction makes sense. I think it could be scrapped, as it's a lot of logic that simply binds it to the `fake-timers` project. That would have made this issue never arise as well. In any case, missing docs is the biggest culprit, I assume.
