### ISSUE TITLE
[Docs] Should docs be updated or removed?

### ISSUE THREAD

**Issue by codejedi365** [sinonjs/nise#186]
sinonjs/nise team,

I recently opened PR [#2365](https://github.com/sinonjs/sinon/pull/2365) to the main sinonjs/sinon repository which I suspect are the docs for the main website https://sinonjs.org.  I noticed you use an automated framework for building the website through the release-source folder so I modified those files to describe sinonjs/nise usage.

On the contrary, I also found in this repository `docs/index.md` which is in a slightly different format (likely since it describes how to use nise directly).  Is this doc file still used & pulled in during build-docs, should it be deleted, or should I modify to match the PR I made on sinonjs/sinon?

**Comment by fatso83** [comment]
Hi, @codejedi365 . Appreciate all your recent efforts! Keeping the subprojects and the main project in sync is a pain point. We are well aware of this, but someone needs to make a directed effort at pushing https://github.com/sinonjs/sinon/issues/1651 forward. We are talking about this internally, since this issue has barely moved an inch in the three years since it opened.

I think you find your questions answered there. (And no, do not delete the file :) )
