### ISSUE TITLE
Update @sinonjs/fake-timers dep

### ISSUE THREAD

**Issue by mahnunchik** [sinonjs/nise#217]
Please update `@sinonjs/fake-timers` dependency to latest one to match `sinon`

**Comment by mahnunchik** [comment]
@fatso83 when is the release planned?

**Comment by fatso83** [comment]
Good reminder. Did the upgrade at work, but something about the network makes all cloud tests using Sauce Labs fail both with and without the work VPN, so I had to do it off-site and just forgot :-) Then I had to figure out why the post-commit script (Husky) failed. Turns out all Husky versions > 4 fails (how hard can it be to create a Git hook?), so had to revert it. But now it should be good (famous last words) 😅
